const lang = {
    en: {
        AT_LEAST: `at least`,
        CHARACTERS_LONG: `characters long`,
        CHARACTERS_OR_LESS: `characters or less`,
        EMAIL_ADDRESS: `Email Address`,
        EMAIL_IS_REQUIRED: `Email is required`,
        FULL_NAME: `Full Name`,
        FULL_NAME_REQUIRED: `Full Name is required`,
        FULL_NAME_MUST_BE: `Full Name must be`,
        INVALID_EMAIL_ADDRESS: `Invalid email address`,
        MESSAGE_MUST_BE: `Your message must be`,
        MESSAGE_SENT: `Thank you, your message has been sent!`,
        MESSAGE_TEXT_IS_REQUIRED: `A message text is required`,
        ONE_SECOND: `One second please...`,
        SENDING_FAILED: `Oops :-( sending failed. Error`,
        PLEASE_SELECT: `Please select...`,
        PLEASE_SELECT_SUBJECT: `Please select one subject`,
        SUBMIT: `Submit`,
        YOUR_MESSAGE: `Your message`,
    },
    de: {
        AT_LEAST: `wenigstens`,
        CHARACTERS_LONG: `Zeichen lang`,
        CHARACTERS_OR_LESS: `Zeichen oder weniger`,
        EMAIL_ADDRESS: `Email Adresse`,
        EMAIL_IS_REQUIRED: `Email ist erforderlich`,
        FULL_NAME: `Vollständiger Name`,
        FULL_NAME_REQUIRED: `Name ist nicht vollständig`,
        FULL_NAME_MUST_BE: `Vollständiger Name muss`,
        INVALID_EMAIL_ADDRESS: `Fehlerhafte Email Adresse`,
        MESSAGE_MUST_BE: `Deine Nachricht muss`,
        MESSAGE_SENT: `Danke, deine Nachricht wurde versendet!`,
        MESSAGE_TEXT_IS_REQUIRED: `Eine Nachricht ist erforderlich`,
        ONE_SECOND: `Einen Moment bitte...`,
        SENDING_FAILED: `Senden abgebrochen. Fehler`,
        PLEASE_SELECT: `Bitte auswählen...`,
        PLEASE_SELECT_SUBJECT: `Bitte ein Thema wählen`,
        SUBMIT: `Abschicken`,
        YOUR_MESSAGE: `Deine Nachricht`,
    },
	ru: {
        AT_LEAST: `по крайней мере`,
        CHARACTERS_LONG: `символов`,
        CHARACTERS_OR_LESS: `символов или меньше`,
        EMAIL_ADDRESS: `Email Адрес`,
        EMAIL_IS_REQUIRED: `Требуется Email`,
        FULL_NAME: `Полное Имя`,
        FULL_NAME_REQUIRED: `Требуется полное имя`,
        FULL_NAME_MUST_BE: `Полное имя должно быть`,
        INVALID_EMAIL_ADDRESS: `Неверный адрес электронной почты`,
        MESSAGE_MUST_BE: `Ваше сообщение должно быть`,
        MESSAGE_SENT: `Спасибо! Ваше сообщение было отправлено!`,
        MESSAGE_TEXT_IS_REQUIRED: `Требуется текст сообщения`,
        ONE_SECOND: `Одну секунду пожалуйста...`,
        SENDING_FAILED: `Упс :-( отправка не удалась. Ошибка`,
        PLEASE_SELECT: `Пожалуйста выберите...`,
        PLEASE_SELECT_SUBJECT: `Пожалуйста, выберите одну тему`,
        SUBMIT: `Отправить`,
        YOUR_MESSAGE: `Ваше сообщение`,
    },
}

module.exports = lang
